version: '2'
services:
  local:
    container_name: reg-local
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      - DELETE_ENABLED=true
    volumes:
      - ~/data/registry:/var/lib/registry
    ports:
      - 5000:5000
    networks:
      - registry-net
  gcr:
    container_name: reg-gcr
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      - PROXY_REMOTE_URL=https://gcr.io
    volumes:
      - ~/data/registry:/var/lib/registry
    networks:
      - registry-net
  k8s-gcr:
    container_name: reg-k8s-gcr
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      - PROXY_REMOTE_URL=https://k8s.gcr.io
    volumes:
      - ~/data/registry:/var/lib/registry
    networks:
      - registry-net
  ghcr:
    container_name: reg-ghcr
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      - PROXY_REMOTE_URL=https://ghcr.io
    volumes:
      - ~/data/registry:/var/lib/registry
    networks:
      - registry-net
  
  ui:
    container_name: reg-ui
    image: joxit/docker-registry-ui
    restart: always
    links:
      - local:reg-local
    environment:
      - REGISTRY_TITLE=Linuxhub Public Container Registry
      - REGISTRY_URL=http://reg-local:5000
      - DELETE_IMAGES=true
    networks:
      - registry-net

  caddy:
    container_name: reg-caddy
    image: ghcr.io/linuxhub-group/caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - ui:reg-ui
      - gcr:reg-gcr
      - k8s-gcr:reg-k8s-gcr
      - ghcr:reg-ghcr
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.caddy/data:/data
      - ./.caddy/config/:/config
    networks:
      - registry-net
    env_file:
      - .env

networks:
  registry-net:

