version: '2'
services:
  local:
    container_name: reg-local
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      - DELETE_ENABLED=true
    volumes:
      - ./.data/registry:/var/lib/registry
    ports:
      - 5000:5000

  gcr:
    container_name: reg-gcr
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      - PROXY_REMOTE_URL=https://gcr.io
    volumes:
      - ./.data/registry:/var/lib/registry
    ports:
      - 5001:5000

  k8s-gcr:
    container_name: reg-k8s-gcr
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      - PROXY_REMOTE_URL=https://k8s.gcr.io
    volumes:
      - ./.data/registry:/var/lib/registry
    ports:
      - 5002:5000

  ghcr:
    container_name: reg-ghcr
    image: findsec/registry-proxy:latest
    restart: always
    environment:
      - PROXY_REMOTE_URL=https://ghcr.io
    volumes:
      - ./.data/registry:/var/lib/registry
    ports:
      - 5003:5000
  
  ui:
    container_name: reg-ui
    image: joxit/docker-registry-ui
    restart: always
    environment:
      - REGISTRY_TITLE=Linuxhub Public Container Registry
      - NGINX_PROXY_PASS_URL=http://reg-local:5000
      - DELETE_IMAGES=true
    env_file:
      - .env
    ports:
      - 801:80

